name: Run Tests
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Setup env
        run: |
          pip install --upgrade pip
          pip install -e . --no-cache-dir
          pip uninstall rltk -y
          pip install git+https://github.com/usc-isi-i2/rltk.git@fix-tokenizer#egg=rltk
          pip install coverage coveralls
      - name: Run Tests
        run: |
          coverage run --source=tl --omit=tl/unittests/test_* -m unittest discover
      - name: Coverage
        env:
          GITHUB_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
        run: |
          coveralls --service=github
