name: Run Tests
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Setup env
        run: |
          pip install --upgrade pip
          pip install -e .
      - name: Run Tests
        run: |
          cd tl/unittests
          python -m unittest discover
